users:
  - github: Sangyoon98
    slack: U09KPG73BGT
    email: qlrqod123123@naver.com
  - github: CHOOSLA
    slack: U09KN753CM9
    email: cnckddn0146@gmail.com
  - github: vivivim
    slack: U09L3CFGMN0
    email: sung.hyunjoo247@gmail.com  
  - github: Lee-Jong-Jin
    slack: U09LQ7D22KA
    email: ljj61111@gmail.com
  - github: taemin3
    slack: U09LTRMB1G8
    email: xoals8534@gmail.com
  - github: yangjiseonn
    slack: U09LTRUMTME
    email: yangjiseonn@gmail.com
