# YOUR_ORGANIZATION/.github/.github/workflows/reusable-assign-issue-creator.yml

name: Reusable - Assign Issue Creator

# on: workflow_call 로 변경하여 다른 워크플로우가 호출할 수 있도록 합니다.
on:
  workflow_call:

permissions:
  issues: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: 이슈 발행자 등록
        uses: actions/github-script@v7
        with:
          script: |
            // context는 호출한 워크플로우의 context를 그대로 이어받습니다.
            const creator = context.payload.issue.user.login;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [creator]
            });
            console.log(`✅ Assigned #${context.issue.number} to ${creator}`);